/*******************************************************************************
* FILE NAME: ws_sync_serial.h
*
* DESCRIPTION: 
*  Provides sync serial support to general IO pins on the RC
*
* USAGE:
*  This file should not be modified by the user.
*  DO NOT EDIT THIS FILE!
*******************************************************************************/

#ifndef __WS_SYNC_SERIAL_H_
#define __WS_SYNC_SERIAL_H_

#ifndef CYGWIN_IFI_SIMULATOR
  /* Real target build */

#else
  /* Simulator build */

#endif

/* Register definitions for talking to the Agilent Mouse with sync serial */
#define AGILENT_MOUSE_CONFIG_REG     0x00 /* RW-Force reset,awake,powerdown */
#define AGILENT_MOUSE_STATUS_REG     0x01 /* RO-Product ID and Awake state */
#define AGILENT_MOUSE_DELTA_Y_REG    0x02 /* RO-Y movement since last read */
#define AGILENT_MOUSE_DELTA_X_REG    0x03 /* RO-X movement since last read */
#define AGILENT_MOUSE_SQUAL_REG      0x04 /* RO-The surface quality (feature/2) */
#define AGILENT_MOUSE_MAX_PIXEL_REG  0x05 /* RO-The max pixel value in the frame */
#define AGILENT_MOUSE_MIN_PIXEL_REG  0x06 /* RO-The min pixel value in the frame */
#define AGILENT_MOUSE_PIXEL_SUM_REG  0x07 /* RO-Average pixel value in the frame */
#define AGILENT_MOUSE_PIXEL_DATA_REG 0x08 /* RW-Ability to dump the pixel image */
#define AGILENT_MOUSE_SHUTTER_UPPER_REG   0x09 /* RO-MSBs of Shutter Reg */
#define AGILENT_MOUSE_SHUTTER_LOWER_REG   0x0A /* RO-LSBs of Shutter Reg */
#define AGILENT_MOUSE_INVERSE_PRODUCT_REG 0x11 /* RO-Inverse of product ID = 0x?F */

/*******************************************************************************
                           FUNCTION PROTOTYPES
*******************************************************************************/

/* These funcs will send/recv data out the sync serial port we have created
 * with the digital IO pins.
 */
unsigned char ReadSyncSerialData(unsigned char addr);
void WriteSyncSerialData(unsigned char addr, unsigned char data);
unsigned char RecvSyncSerialByte(void);
void SendSyncSerialByte(unsigned char data);

#endif


/******************************************************************************/
/******************************************************************************/
/******************************************************************************/
